### PR TITLE
Atomic HRS reads

### PR DESCRIPTION
**Pull request by mark9064**
- Combines the reading of all HRS3300 registers into one I2C read so data is not partial
- Downsizes both HRS and ALS to 16bit as the sensor does not generate larger than 16bit values in its current configuration
  - Increasing the resolution by 1 bit doubles the sensor acquisition time, since we are already at 10Hz we are never going to use a higher resolution
  - The PPG algorithm buffers for ALS/HRS are already 16bit anyway
- Removes functions for setting gain / drive that are unused throughout the codebase

### CODE REVIEW

**Review by JF002 — APPROVED** [review]

File: src/drivers/Hrs3300.cpp [hunk 1]
```diff
@@ -67,40 +67,27 @@ void Hrs3300::Disable() {
...
-  en = (en & 0xf7) | ((drive & 2) << 2);
-  pd = (pd & 0xbf) | ((drive & 1) << 6);
-
-  WriteRegister(static_cast<uint8_t>(Registers::Enable), en);
-  WriteRegister(static_cast<uint8_t>(Registers::PDriver), pd);
+  // hrs
+  uint8_t m = static_cast<uint8_t>(Registers::C0DataM) - base;
+  uint8_t h = static_cast<uint8_t>(Registers::C0DataH) - base;
+  uint8_t l = static_cast<uint8_t>(Registers::C0dataL) - base;
+  res.hrs = (buf[m] << 8) | ((buf[h] & 0x0f) << 4) | (buf[l] & 0x0f);
```
[the remark this answers is not in the document]
Comment (mark9064) [reply src/drivers/Hrs3300.cpp:82]: It reads the top two bits (bit 17 and 18). We're never using to use 17+bit resolution on this sensor as it takes ~200 and ~400ms respectively to sample at those resolutions - unusable for HR measurement (at 5Hz or 200ms per sample, the maximum possible frequency is 2.5Hz (always half the sampling rate) which is only 150bpm). Also, the value is truncated 16bit inside the the PPG algorithm

File: src/drivers/Hrs3300.cpp [hunk 2]
```diff
@@ -67,40 +67,27 @@ void Hrs3300::Disable() {
...
-
-void Hrs3300::SetGain(uint8_t gain) {
-  constexpr uint8_t maxGain = 64U;
-  gain = std::min(gain, maxGain);
-  uint8_t hgain = 0;
-  while ((1 << hgain) < gain) {
-    ++hgain;
+Hrs3300::PackedHrsAls Hrs3300::ReadHrsAls() {
+  uint8_t buf[8];
+  uint8_t base = static_cast<uint8_t>(Registers::C1dataM);
```
[the remark this answers is not in the document]
Comment (mark9064) [reply src/drivers/Hrs3300.cpp:72]: I mean if you really wanted it would be possible to compute the relative offsets at compile time with constexpr. 
```c++
  constexpr Registers dataRegisters[] =
    {Registers::C1dataM, Registers::C0DataM, Registers::C0DataH, Registers::C1dataH, Registers::C1dataL, Registers::C0dataL};
  constexpr uint8_t base = static_cast<uint8_t>(*std::min_element(std::begin(dataRegisters), std::end(dataRegisters)));
  ```
Would work.

But it seems contrived to me as the register locations are never going to change for this chip, and this file is a chip specific driver

[the remark this answers is not in the document]
Comment (NeroBurner) [reply src/drivers/Hrs3300.cpp:72]: yes, the constexpr solution seems very nice. Otherwise `base` just seemed magic to me when reading the changes for the first few times. With constexpr the way `base` is determined is now explicit. And we don't have runtime overhead for this computation. Win-Win in my opinion :)

As I'm not much in the drivers area I may need more "handholding" than others :sweat_smile:

File: src/drivers/Hrs3300.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (NeroBurner) [reply src/drivers/Hrs3300.cpp:82]: very good reasoning, thanks!

**Review by NeroBurner — CHANGES_REQUESTED** [review]
just the constexpr documentation please and then we're good to go from my side

**Comment by mark9064** [comment]
Thought I may as well calculate the required buffer length too. Fewer magic numbers

**Review by NeroBurner — APPROVED** [review]
temporarily hit a compiler bug in with InfiniSim with gcc 14.2.1. Worked on gcc 14.1.1 and gcc 13.3.0 and and clang 18.1.8. Reinstalled 14.2.1 to generate the error message... and gone.

So looks good to me. Especially the constexpr stuff :)

**Comment by NeroBurner** [comment]
Well seems to be back :see_no_evil: 

```
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp: In member function ‘Pinetime::Drivers::Hrs3300::PackedHrsAls Pinetime::Drivers::Hrs3300::ReadHrsAls()’:
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:74:83: error: no matching function for call to ‘begin(const Pinetime::Drivers::Hrs3300::Registers [6])’
[build]    74 |   constexpr uint8_t baseOffset = static_cast<uint8_t>(*std::min_element(std::begin(dataRegisters), std::end(dataRegisters)));
[build]       |                                                                         ~~~~~~~~~~^~~~~~~~~~~~~~~
[build] In file included from /usr/include/c++/14.2.1/bits/algorithmfwd.h:39,
[build]                  from /usr/include/c++/14.2.1/bits/stl_algo.h:59,
[build]                  from /usr/include/c++/14.2.1/algorithm:61,
[build]                  from /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:8:
[build] /usr/include/c++/14.2.1/initializer_list:88:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::begin(initializer_list<_Tp>)’
[build]    88 |     begin(initializer_list<_Tp> __ils) noexcept
[build]       |     ^~~~~
[build] /usr/include/c++/14.2.1/initializer_list:88:5: note:   template argument deduction/substitution failed:
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:74:83: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘const Pinetime::Drivers::Hrs3300::Registers*’
[build]    74 |   constexpr uint8_t baseOffset = static_cast<uint8_t>(*std::min_element(std::begin(dataRegisters), std::end(dataRegisters)));
[build]       |                                                                         ~~~~~~~~~~^~~~~~~~~~~~~~~
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:74:108: error: no matching function for call to ‘end(const Pinetime::Drivers::Hrs3300::Registers [6])’
[build]    74 |   constexpr uint8_t baseOffset = static_cast<uint8_t>(*std::min_element(std::begin(dataRegisters), std::end(dataRegisters)));
[build]       |                                                                                                    ~~~~~~~~^~~~~~~~~~~~~~~
[build] /usr/include/c++/14.2.1/initializer_list:99:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::end(initializer_list<_Tp>)’
[build]    99 |     end(initializer_list<_Tp> __ils) noexcept
[build]       |     ^~~
[build] /usr/include/c++/14.2.1/initializer_list:99:5: note:   template argument deduction/substitution failed:
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:74:108: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘const Pinetime::Drivers::Hrs3300::Registers*’
[build]    74 |   constexpr uint8_t baseOffset = static_cast<uint8_t>(*std::min_element(std::begin(dataRegisters), std::end(dataRegisters)));
[build]       |                                                                                                    ~~~~~~~~^~~~~~~~~~~~~~~
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:77:79: error: no matching function for call to ‘begin(const Pinetime::Drivers::Hrs3300::Registers [6])’
[build]    77 |   constexpr uint8_t length = static_cast<uint8_t>(*std::max_element(std::begin(dataRegisters), std::end(dataRegisters))) - baseOffset + 1;
[build]       |                                                                     ~~~~~~~~~~^~~~~~~~~~~~~~~
[build] /usr/include/c++/14.2.1/initializer_list:88:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::begin(initializer_list<_Tp>)’
[build]    88 |     begin(initializer_list<_Tp> __ils) noexcept
[build]       |     ^~~~~
[build] /usr/include/c++/14.2.1/initializer_list:88:5: note:   template argument deduction/substitution failed:
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:77:79: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘const Pinetime::Drivers::Hrs3300::Registers*’
[build]    77 |   constexpr uint8_t length = static_cast<uint8_t>(*std::max_element(std::begin(dataRegisters), std::end(dataRegisters))) - baseOffset + 1;
[build]       |                                                                     ~~~~~~~~~~^~~~~~~~~~~~~~~
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:77:104: error: no matching function for call to ‘end(const Pinetime::Drivers::Hrs3300::Registers [6])’
[build]    77 |   constexpr uint8_t length = static_cast<uint8_t>(*std::max_element(std::begin(dataRegisters), std::end(dataRegisters))) - baseOffset + 1;
[build]       |                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~
[build] /usr/include/c++/14.2.1/initializer_list:99:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::end(initializer_list<_Tp>)’
[build]    99 |     end(initializer_list<_Tp> __ils) noexcept
[build]       |     ^~~
[build] /usr/include/c++/14.2.1/initializer_list:99:5: note:   template argument deduction/substitution failed:
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:77:104: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘const Pinetime::Drivers::Hrs3300::Registers*’
[build]    77 |   constexpr uint8_t length = static_cast<uint8_t>(*std::max_element(std::begin(dataRegisters), std::end(dataRegisters))) - baseOffset + 1;
[build]       |                                                                                                ~~~~~~~~^~~~~~~~~~~~~~~
[build] /home/nero/repos/pinetime/InfiniSim/InfiniTime/src/drivers/Hrs3300.cpp:80:15: error: size of array ‘buf’ is not an integral constant-expression
[build]    80 |   uint8_t buf[length];
[build]       |               ^~~~~~
```

and I get rid of it including `<vector>` after `<algorithm>`??? something is definitely going on with `gcc 14.2.1` :see_no_evil:

**Comment by mark9064** [comment]
Strange that it's intermittent. If adding some headers fixes it I suppose it doesn't hurt to?

**Comment by NeroBurner** [comment]
after more investigating I can say, not a compiler bug. GCC 14 is now more correct and somewhere cleaned up their stlib headers.
We use `std::begin`, but we don't include any headers that define `std::begin`

List of headers that define `std::begin` `std::end` (from: https://en.cppreference.com/w/cpp/iterator/begin )

```
Defined in header [<array>](https://en.cppreference.com/w/cpp/header/array)
Defined in header [<deque>](https://en.cppreference.com/w/cpp/header/deque)
Defined in header [<flat_map>](https://en.cppreference.com/w/cpp/header/flat_map)
Defined in header [<flat_set>](https://en.cppreference.com/w/cpp/header/flat_set)
Defined in header [<forward_list>](https://en.cppreference.com/w/cpp/header/forward_list)
Defined in header [<inplace_vector>](https://en.cppreference.com/w/cpp/header/inplace_vector)
Defined in header [<iterator>](https://en.cppreference.com/w/cpp/header/iterator)
Defined in header [<list>](https://en.cppreference.com/w/cpp/header/list)
Defined in header [<map>](https://en.cppreference.com/w/cpp/header/map)
Defined in header [<regex>](https://en.cppreference.com/w/cpp/header/regex)
Defined in header [<set>](https://en.cppreference.com/w/cpp/header/set)
Defined in header [<span>](https://en.cppreference.com/w/cpp/header/span)
Defined in header [<string>](https://en.cppreference.com/w/cpp/header/string)
Defined in header [<string_view>](https://en.cppreference.com/w/cpp/header/string_view)
Defined in header [<unordered_map>](https://en.cppreference.com/w/cpp/header/unordered_map)
Defined in header [<unordered_set>](https://en.cppreference.com/w/cpp/header/unordered_set)
Defined in header [<vector>](https://en.cppreference.com/w/cpp/header/vector)
```

Opened a PR: https://github.com/InfiniTimeOrg/InfiniTime/pull/2128
